### PR TITLE
Extending Expect

### LINKED ISSUE #126: Document Extending Expect
Thanks to lovely OO we can extend the Expect function so that people can create their own custom assertions e.g. `Expect(hexCode).isColor()`

Add some documentation as to how to do it.

### PR DESCRIPTION
**Pull request by jamesrichford**
# Description
Added documentation and rework to enable extending expect. Closes #126

# Checklist

- [x] I am an awesome developer and proud of my code
- [x] I added / updated / removed relevant unit or integration tests to prove my change works
- [x] I ran all tests using ```npm test``` to make sure everything else still works
- [x] I ran ```npm run review``` to ensure the code adheres to the repository standards

### CODE REVIEW

**Comment by Jameskmonger** [comment]
I think we need some notes on how to actually use `ExtendedMatcher`

**Comment by jamesrichford** [comment]
@Jameskmonger - go for it :)

**Comment by Jameskmonger** [comment]
Feels odd that we extend `Matcher` but still get `toBeEqual` etc from `Extend`...

**Comment by jamesrichford** [comment]
@jameskmonger this is because the ```Expect``` function is just a wrapper to give nice sugar for writing tests out (avoiding writing new) while the functionality is in the class. I've toyed with casting the constructor exported to a function that returns the type but that causes issues with extension. Also having a static function that calls the constructor on matcher but just seems pretty much the same as what we've got. I'd say we could make a swap to the second in version 2 but we're catering for the few who want to extend it rather than the everyone who wants to use it.

When extending of course there's no reason you can't implement one of the above :)

**Pull request merged**
