### PR TITLE
Add TapBark config option to define output elements order

### LINKED ISSUE #540: Any way to suppress stack trace?
There are some instances where I want to display just the number of passing/failing/skipped tests, for example as a very basic health display on a monitor.

The stack trace can get in the way and push the results off the top of the screen, meaning manual intervention is needed to scroll back up.

I am using a Node script as per the [Running Tests doc](https://github.com/alsatian-test/alsatian/wiki/running-tests). Is there any way I can suppress the stack trace?

### PR DESCRIPTION
**Pull request by benji7425**
## Description

Adds a `resultsOrder` parameter to method `TapBark.create()` to facilitate custom ordering of the results printed to the console.

Will close #540 when complete.

## Incomplete

I'm unfamiliar with React, Ink and using .tsx files so I have had some formatting issues. I can't see how, but when using this in my own projects the failures format wrong. I'm probably missing something obvious, but can't immediately see what it is.
image

I also had problems getting the project fully working on my Windows 10 machine - I assume you are using Linux or Mac OS. I did spend a while trying to troubleshoot but in the end it didn't seem fully worth. I had to re-execute `npm run bootstrap` every time I wanted to do anything, and I wasn't able to get `npm test` working at all.
Anyway, the result is that I haven't validated that all the tests still pass.

Would appreciate some assistance getting this PR fully merge-ready as I don't have lots of spare time to troubleshoot. No offence taken if you reject it, or want to change most of it.

### CODE REVIEW

**Comment by jamesadarich** [comment]
Thanks for this!

I think the best way forward here would be if we don't make it configurable to order the elements and just reorder them in your preferred sort (summary last). Will that work for you?

**Comment by benji7425** [comment]
That's fine by me, but I don't want to assume the workflow of others. It annoys me this way round, but might annoy someone else the other way around, especially if they are used to it. I thought it might be better to leave existing clients as is, with the option to re-order for those who want to. Thougts?

**Comment by jamesadarich** [comment]
I think it sounds like a good general change to have details above the summary especially in the case of CI but even in CLI output you can understand scale before needing to look at detail. It's a visual change and we can always look at options if necessary so with that in mind I think we're quite safe to change this :)

**Comment by benji7425** [comment]
Fair enough. Seems kind of token effort, but [here you go](https://github.com/alsatian-test/alsatian/pull/551)

**Comment by jamesadarich** [comment]
The value is in the result not the amount of code - so this is appreciated :)

**Pull request closed without merging**
