### PR TITLE
Use tap output for travis

### PR DESCRIPTION
**Pull request by Jameskmonger**
# Description

Use TAP output for Travis.

# Checklist

- [x] I am an awesome developer and proud of my code
- [x] I added / updated / removed relevant unit or integration tests to prove my change works
- [x] I ran all tests using ```npm test``` to make sure everything else still works
- [x] I ran ```npm run review``` to ensure the code adheres to the repository standards

# Additional Information

### CODE REVIEW

**Comment by jamesrichford** [comment]
Hey dude, what's the reason for this change?

**Comment by Jameskmonger** [comment]
It doesn't look like Travis handles the way that tap-bark does the cool "undo-and-rewrite" stuff, so it comes out looking awful.

Take a look here:

https://travis-ci.org/alsatian-test/alsatian/jobs/167610895

**Comment by jamesrichford** [comment]
maybe worth checking if can tweek tap-bark to output a bit neater?

**Comment by Jameskmonger** [comment]
I agree @jamesrichford

**Comment by jamesrichford** [comment]
OK I'll close this for now and raise an issue on tap bark @jameskmonger

**Pull request closed without merging**
