### PR TITLE
3.0.0

### PR DESCRIPTION
**Pull request by jamesadarich**
# Description
Tracking release 3.0.0 progress

# Checklist

- [x] I am an awesome developer and proud of my code
- [x] I added / updated / removed relevant unit or integration tests to prove my change works
- [x] I ran all tests using ```npm test``` to make sure everything else still works
- [x] I ran ```npm run review``` to ensure the code adheres to the repository standards

### CODE REVIEW

**Comment by gobengo** [comment]
@jamesadarich Love this lib. What's blocking this?

**Comment by jamesadarich** [comment]
@gobengo thanks, trying to get it sorted asap. Just life getting in the way a bit. I've made progress recently and got a few issues to iron out on the Expect refactor and should hopefully be ready with a beta soon :) then after that just minor tidies until the full release

**Comment by gobengo** [comment]
@jamesadarich Great! I understand the life bit. Cheering you on!

**Comment by jamesadarich** [comment]
@gobengo beta release has just gone out, just final tidy ups now. Have a peek if you have a chance, I'd appreciate feedback / will resolve any bugs you find asap :)

**Comment by gobengo** [comment]
@jamesadarich I've been using it the last week or so. So far so good!

btw, with Alsatian I almost always use copy paste this pattern into my project. I should make it a lib or something, but you may also want to incorporate it as a helper into the core/official packages.

I want to be able to execute my test files one-by-one to run the tests in there, just like any other normal unix script: `./SomeTest.test.ts`. 

This is nice for a number of reasons, including I can easily use a node debugger in the tests I'm writing by hitting 'F5' in vscode to execute the current file.

In my test files I do:
```
import "../path-to/alsatian-cli"
if (require.main === module) {
  (async () {
    await cli(__filename);
  })();
}
```

src/test/alsatian-cli.ts
```
import { TestOutputStream, TestRunner, TestSet } from "alsatian";
import { join } from "path";
import { Duplex } from "stream";
import { TapBark } from "tap-bark";

type TestCLI = (filesOrGlobs: string | string[]) => Promise<void>;

/**
 * Test CLI
 * If passed a filename, will run test in that file.
 * Otherwise, run tests in all files.
 */
export const cli: TestCLI = async (
  filesOrGlobs: string | string[],
): Promise<void> => {
  process.on("unhandledRejection", error => {
    console.error(error);
    throw error;
  });
  await main(filesOrGlobs);
};

/**
 * Run all tests
 */
async function main(filesOrGlobs: string | string[]): Promise<void> {
  // Setup the alsatian test runner
  const testRunner: TestRunner = new TestRunner();
  const tapStream: TestOutputStream = testRunner.outputStream;
  const testSet: TestSet = TestSet.create();
  testSet.addTestsFromFiles(filesOrGlobs);

  // This will output a human readable report to the console.
  const bark = TapBark.create();
  const barkTransform = bark.getPipeable();
  tapStream.pipe(barkTransform).pipe(process.stdout);

  // Runs the tests
  const timeout = process.env.TEST_TIMEOUT_MS
    ? parseInt(process.env.TEST_TIMEOUT_MS, 10)
    : 60 * 1000;
  await testRunner.run(testSet, timeout);
}

type Decorator = (
  target: object,
  propertyKey: string,
  descriptor?: TypedPropertyDescriptor<any>,
) => void;
/** Conditionally apply a decorator */
export function DecorateIf(
  test: () => boolean,
  decorator: Decorator,
): Decorator {
  if (test()) {
    return decorator;
  }
  return () => {
    return;
  };
}
```

**Comment by jamesadarich** [comment]
Is the goal here to ensure that tests run sequentially? Because that should already be happening. Could you open an issue for this to discuss further please?

**Pull request merged**
