### PR TITLE
Feature/issue308 test case arguments

### PR DESCRIPTION
**Pull request by Nysosis**
# Description

Fixes issue #308 with case arguments not being emitted to output

# Checklist

- [x] I am an awesome developer and proud of my code
- [x] I added / updated / removed relevant unit or integration tests to prove my change works
- [x] I ran all tests using ```npm test``` to make sure everything else still works
- [x] I ran ```npm run review``` to ensure the code adheres to the repository standards

### CODE REVIEW

**Comment by Jameskmonger** [comment]
See my comment on #302 https://github.com/alsatian-test/alsatian/pull/312#issuecomment-280301454

**Comment by Nysosis** [comment]
Shall I close this one as #312 got merged in?

**Comment by jamesrichford** [comment]
@Nysosis nope let's keep this one open as @Jameskmonger just needs to complete his review so it can get merged to master. I was thinking though additionally it would be good to get an integration test in for this to help avoid regression again. Would you like some explanation as to how to go about this? Also I'm happy to do it as well so not a big deal :)

**Comment by Nysosis** [comment]
@jamesrichford I've got an integration test I've just whipped up, just a bit worried about the potential brittleness of it. Expecting the following output:

```
TAP version 13
1..6
# FIXTURE CaseArgumentTestsTests
ok 1 AddNumbers ( 1, 2, 3 )
ok 2 AddNumbers ( 1.5, 2.5, 4 )
ok 3 AddStrings ( "Hello", " world!", "Hello world!" )
ok 4 AddStrings ( "Far", "away", "Faraway" )
ok 5 AddObjectProperty ( {"a":1}, {"a":2}, 3 )
ok 6 AddArray ( [1,2], [3,4], 10 )
```

However the formatting of the arguments in `AddObjectProperty` and `AddArray` are dependent upon the serialisation that JSON will do, which I don't know if it's identical cross-platform (I'm guessing it would be, but JS is full of quirks!). However if it's not, either now or in the future that's going to break.

I could drop those cases from the test, and just stick to string/number primitives, as I think all we really care about is whether we're getting any display of arguments, because (I think) there are other tests covering the expected generated output for test cases using the involved classes, so if anything changes there they would pick up on it, without it impacting this integration test

**Comment by jamesrichford** [comment]
@Nysosis good thoughts - I've just got a Windows CI setup in place in #313 so I'm going to merge this so that we are at least notified if there is an environment based difference in the stringification. If we find that there is then we can make a decision as to what to do otherwise it should be fine to keep these tests in as it will highlight if there is a change on a future setup.

Plus it's always better to have more thorough tests and it would be a shame to waste them :)

**Comment by Nysosis** [comment]
Ok, so whats the best way to get the integration tests in?
* Just update this PR, and leave 1.2.x without?
* Update this PR, and do a new PR for 1.2.x
* Do two new PRs one for master and one for 1.2.x

**Comment by jamesrichford** [comment]
@Nysosis just update this PR we only need the integration tests going forward, the branch is just to patch issues with that release so should be fine to leave without :)

**Comment by jamesrichford** [comment]
Hey @Nysosis - looks like integration tests are failing. May need to update the gulp tests (maybe others too)

**Comment by Nysosis** [comment]
@jamesrichford Thanks, my bad, thought I'd re-run the entire test suite after adding those tests in, guess not! Just committed a fix up

**Comment by Jameskmonger** [comment]
@jamesrichford Coveralls is going crazy again! Maybe we could look into just measuring our own coverage using istanbul, and having it as part of the build checks. I'd really prefer not to have so many coveralls messages in every thread.

**Comment by jamesrichford** [comment]
@jameskmonger it does publish the coverage changes nicely though so that's a positive. I'll find out if I can disable the comments though and just have the approval

**Comment by jamesrichford** [comment]
@jameskmonger - comments should now be disabled. You'll have to do some work so we can test with a PR ;)

**Comment by jamesrichford** [comment]
Awesome work, thanks @Nysosis

**Pull request merged**
