### PR TITLE
Adding experimental FluentExpect API

### PR DESCRIPTION
**Pull request by cdibbs**
# Description

This is a first draft of the FluentExpect API I described in https://github.com/alsatian-test/alsatian/issues/454. It has a suite of tests with 100% coverage, but I wouldn't say its production-ready. It's ready to poke at and experiment with! From here, I plan to switch gears and start using it in another project, to work out any kinks.

There is a rough draft of several wiki pages describing the available methods. https://github.com/cdibbs/alsatian/wiki

# Checklist

- [x] I am an awesome developer and proud of my code
- [x] I added / updated / removed relevant unit or integration tests to prove my change works
- [x] I ran all tests using ```npm test``` to make sure everything else still works
- [x] I ran ```npm run review``` to ensure the code adheres to the repository standards

# Additional Information

### CODE REVIEW

**Comment by cdibbs** [comment]
FYI I am working on the fixable codeclimate issues. Hope to be done, soon.

**Comment by cdibbs** [comment]
Ok, the more important codeclimate issues are fixed. Most of the rest revolve around method aliases (code redundancy). Let me know if you think anything should be done about these, too. Thanks!

**Comment by jamesrichford** [comment]
Hey @cdibbs, thanks for this. I'm afraid daddy duties haven't let me review this in full yet but first thought is I'm interested in some of these proposed matchers but the thing I do wonder is the benefit of `to` `with` etc. properties over `toMatch` `toBe` `withProperties` for me it has detractors:

* masks matchers that chain on from it - makes them less explorable
* adds an extra level of properties so typing can't shortcut as easily using intellisense
* not as optimal use of strong typing - `Expect` matchers are currently filtered by the type passed in but this won't be the case as much here

What would be the benefits of using these properties?

**Comment by cdibbs** [comment]
@jamesrichford I agree with your points. I experimented with ditching the stop words, but toward the end of it, I reverted and came to think of them as necessary to keep the API compact, code-wise (you shift most of the English grammar-related aliasing to a stop words class). 

That, for me, was the big issue. Several methods want to narrow the scope, but within the narrowed scope, they would need aliases, or the grammar will be confusing (does "toHave().toHave()" talk about the parent object having two properties, or the property having a subproperty?). I thought this potential for confusion might only increase, as the API grew and evolved.

Maybe there's another option, though:

```typescript
Assert(obj)
  .is(SomeType)
  .has(o => o.prop)
  .that.hasMatch(/(\d+)/) // alt 'matches' that returns match result scope
  .that.has(matchParts => +matchParts[0])
  .that.equals(3);
Assert(obj).equals(expected);
Assert(obj).has({
  myProp: 3,
  other: p => Assert(p).matches(...)
});
```

The `that` word, above, could be functional; it would choose to narrow the assertion scope (vs keep the current scope, when omitted). Also, `has` now gets overloaded in a way that makes sense, and replaces `properties`, and maybe even `elements`.

Ugg. I'm sorry I didn't think of this, before. From just this little exploration, it looks like the API might become more concise, while being less grammatically problematic in a fluent context, just by starting with a different verb. :-) I think it satisfies your three concerns, too. What do you think? Should I refactor and try this?

**Comment by jamesrichford** [comment]
Interesting perspective there @cdibbs :) looks very cool. The only thing I'm thinking is now it's so different (even the core start function moving from `Expect` to `Assert`) should this be an experimental feature that starts inside or outside alsatian OR even an alternative because there are some people that prefer the `Assert` style and others that prefer the `Expect`. Maybe seems like it should be an alternative library that you can choose to import. Any thoughts @Jameskmonger

**Comment by Jameskmonger** [comment]
I do like @cdibbs example, but I agree with you @jamesrichford that it's a very large change. I know now of 5 or 6 very large project using Alsatian. I think that if we made such a change, the majority of users would never adopt it and so would miss out on any future updates.

**Comment by cdibbs** [comment]
Yep, that makes sense to me. Plus, having Assert and Expect in the same library might be confusing. I'll refactor and turn it into its own library. After its done, you could maybe reference it to add properties assertions and whatnot to the default Expect API.

**Comment by jamesrichford** [comment]
Absolutely, thanks for this @cdibbs. Please let us know when you publish and we'll add some links here :)

**Pull request closed without merging**
