### PR TITLE
Fix for the `_checkObjectsAreDeepEqual` to handle nulls correctly

### PR DESCRIPTION
**Pull request by bartlomiejzuber**
# Description

Fix for the `_checkObjectsAreDeepEqual` to handle nulls correctly.

# Checklist

- [x] I ran all tests using ```npm test``` to make sure everything else still works
- [x] I ran ```npm run review``` to ensure the code adheres to the repository standards

# Additional Information

Changes has been done in order to fix this issue: https://github.com/alsatian-test/alsatian/issues/500

### CODE REVIEW

**Comment by jamesadarich** [comment]
Thanks for this one @bartlomiejzuber just trying to finish off the 3.0.0 restructure which may cause a conflict here but I'll resolve it for you so we can get your name to this nice addition :)

**Comment by jamesadarich** [comment]
Ready @bartlomiejzuber if you could put this change against `release/3.0.0` I'll get it merged. The file has changed somewhat I think you'll be looking for `object-matcher.ts`.

If we could also get a test for this that would be perfect :) thanks!!

**Comment by bartlomiejzuber** [comment]
@jamesadarich I did that. :) Good idea with the test, I will try to add it soon. :)

**Comment by jamesadarich** [comment]
Awesome cheers @bartlomiejzuber  👍

**Comment by bartlomiejzuber** [comment]
@jamesadarich I've added one test. Could you please check if it looks good to you ? :)

**Comment by jamesadarich** [comment]
perfect thanks @bartlomiejzuber 👍

**Comment by bartlomiejzuber** [comment]
I am glad I could help. 👍

**Pull request merged**
