### PR TITLE
Allow maps to be passed to the empty expectation

### LINKED ISSUE #462: Allow Map's to be expected to be Empty
First off, thanks for this amazing project! I am enjoying working with it.

Currently I have one request - `toBeEmpty` can only be used with arrays, strings, and object literals. However, I would like to see the `Map` be added since it has the property `size` that returns the amount of records in the map.

### PR DESCRIPTION
**Pull request by graywolf336**
# Description

This allows `Map` to be used in the `toBeEmpty` expectation.

Closes #462 

# Checklist

- [x] I am an awesome developer and proud of my code
- [x] I added / updated / removed relevant unit or integration tests to prove my change works
- [ ] I ran all tests using ```npm test``` to make sure everything else still works
- [x] I ran ```npm run review``` to ensure the code adheres to the repository standards

# Additional Information
I would love to get some feedback on the code inside the `empty-matcher` file, I do *not* like the nested if statements but I couldn't come up with a better way at the time.

As crazy as this sounds, `Map` keys can be anything, including another object. How should the `stringify` function handle them? I put a placeholder there to show the size/length of it, but I know that can be improved so it is less confusing.

Also, some reason the `npm test` command is failing on my Windows machine (I'm away from my usual development environment which is Linux) at the step `npm link && install-self`.

### CODE REVIEW

**Comment by jamesadarich** [comment]
I've had a thought about a refactor here. Perhaps it makes sense to move the logic to more specific classes that all implement a similar interface instead of abstracted to a common function.

E.g. ArrayMatcher, MapMatcher implement the toBeEmpty function from interface IEmptyMatcher.

Should simplify the individual functions. What are your thoughts @graywolf336?

**Comment by graywolf336** [comment]
Sounds like a fantastic idea :+1: would be allow the empty match to be extended with ease, which I like that.

**Comment by jamesadarich** [comment]
Yep @pathurs this sounds like a great plan 👍 I'll create one now, once CI has finished we can get it merged

**Comment by jamesadarich** [comment]
thanks @graywolf336 we'll get this published soon 👍

**Pull request merged**
