### PR TITLE
Update @types/node to 4.0.0

### PR DESCRIPTION
**Pull request by Jameskmonger**
This will make sure our types for node match the engine we're using, and will also stop greenkeeper suggesting we update to 7.x.x

### CODE REVIEW

**Comment by jamesrichford** [comment]
Cool, nice one @Jameskmonger.

Did you investigate #303 at all? as to whether we can change to a peer or optional dependency? or perhaps we don't actually need it anymore in the runtime and it's now just a dev dependency?

**Comment by jamesrichford** [comment]
@Jameskmonger also is ^4.0.0 correct as this is only version 4 whereas we support at least version 4?

**Comment by Jameskmonger** [comment]
As we support version 4 at the lowest, I think `^4.0.0` is correct because that way we ensure compatibility with the lowest Node version.

Ideally we would have `^4.0.0` for Node 4 and `^5.0.0` for Node 5, and so on, but I can't think of a way to do that.

Also I'm unsure which dependency type it should be.

**Comment by jamesrichford** [comment]
@Jameskmonger I meant why not `>=4.0.0`?

Also with respect to what sort of dependency I think regular (see #398 for more info)

**Comment by Jameskmonger** [comment]
`>=4.0.0` will make npm install the latest version of `@types/node` after `4.0.0`, in this case `7.0.23` - this will cause an issue if we are compiling on a Node `4.0.0` environment.

**Comment by jamesrichford** [comment]
Surely only if the project uses the node API itself also in which case the project could `npm install @types/node@4` and that would satisfy both?

**Comment by Jameskmonger** [comment]
I still think it would be best to lock down the Node typings to the lowest supported Node version.

**Comment by jamesrichford** [comment]
I guess the problem with that could be someone wants to use alsatian + a part of the node API introduced after version 4, then they'd have 2 versions of the same typing installed which could conflict with each other?

**Comment by jamesrichford** [comment]
Maybe it could be an optional dependency? It's only really used I think when using the node based runner as opposed to the CLI (e.g. when piping the stream to some output) so could have it such that it's not installed by default but if you want to use this functionality then you do have to?

**Comment by jamesrichford** [comment]
Going round full circle now to peer dependency. Peer will mean that it's not installed by default but the user will get a warning if they don't have it as a dependency i.e. UNMET PEER DEPENDENCY

We can't suppress the warning as is (see https://github.com/npm/npm/issues/3066) but perhaps peer is better as it won't force a version but suggest a range then the user can choose the relevant one?

**Comment by jamesrichford** [comment]
It's just annoying for an additional step but they can ignore the warning if they're not using the node version

**Comment by jamesrichford** [comment]
Right @Jameskmonger I've done some testing on installs and it looks like if we declare a version of `@types/node` and a more specific one is specified by a user that's in our range our version will be replaced by the more specific. So if we declare `>=4.0.0` and a user declares `^4.0.0` the users will be used for both where as if they don't then npm will get the latest. If the user decides to update the types at a later stage this rule will still apply. So probably keeping as dependency but >= makes sense?

**Pull request merged**
