### PR TITLE
Feature/issue308 1.2.x test case arguments

### PR DESCRIPTION
**Pull request by Nysosis**
# Description

Fixes issue #308 with case arguments not being emitted to output

# Checklist

- [x] I am an awesome developer and proud of my code
- [x] I added / updated / removed relevant unit or integration tests to prove my change works
- [x] I ran all tests using ```npm test``` to make sure everything else still works
- [x] I ran ```npm run review``` to ensure the code adheres to the repository standards

### CODE REVIEW

**Comment by Jameskmonger** [comment]
Sorry @Nysosis I know it's not code you introduced, but could we potentially clean this up as part of this fix:

```typescript
if (testCaseArguments !== undefined && testCaseArguments.length > 0) {
    testDescription += ` ( ${testCaseArguments.map(argument =>
        this._getArgumentDescription(caseArgument)
    ).join(", ")} )`;
}
```

**Comment by Nysosis** [comment]
@Jameskmonger What sort of clean up were you thinking of?

**Comment by Jameskmonger** [comment]
I think it's pretty ugly having the `map` function call inside the templated string like that (I think I'm the one who wrote it 😢) - maybe just move that to another function?

    testDescription += formatArguments(testCaseArguments);

**Comment by Nysosis** [comment]
I've fixed up in the #310 pull, as that's the non-branch specific one, what
with the ongoing discussion around whether it's worth back-porting the fix,
if it's agreed to do so, then we can just apply the same tidy up (if
desired) onto those pulls

**Comment by jamesrichford** [comment]
@Nysosis great work! 👍 gonna merge this one in to 1.2 and get it released :) then can check the refactor in the master pull

**Pull request merged**
