### PR TITLE
Fix #100: Move metadata keys to constants file

### LINKED ISSUE #100: Move reflect keys to a constants file

### PR DESCRIPTION
**Pull request by Jameskmonger**

### CODE REVIEW

**Comment by jamesrichford** [comment]
Hey @Jameskmonger 

I'll pick this up tomorrow! :)

**Comment by Jameskmonger** [comment]
Not a clue what coveralls is up to above...

**Comment by jamesrichford** [comment]
Hey @Jameskmonger,

Just a little thought on them being named X_KEY since they are being used as REFLECT_KEYS.X_KEY maybe they already have that context? So remove the KEY part? What do you think?

**Comment by Jameskmonger** [comment]
Happy to do that @jamesrichford :smile: I'll make the changes (and also merge master in to resolve conflicts)

**Comment by jamesrichford** [comment]
:boom:

**Pull request merged**
