### PR TITLE
Log issue loading file

### PR DESCRIPTION
**Pull request by Jameskmonger**
Temporary fix for #421

### CODE REVIEW

**Comment by jamesrichford** [comment]
@Jameskmonger please add unit tests

**Comment by jhm-ciberman** [comment]
Can you please hurry to merge this? Is a pain to test and debug with this bug. 
Also, my CI gives false positives. (Example: https://travis-ci.org/jhm-ciberman/docs_gm/builds/328937778)

**Comment by jamesrichford** [comment]
@Jameskmonger write those tests buddy peeps be waiting!

**Comment by Jameskmonger** [comment]
@jamesrichford This is now ready to be merged. Sorry it took so long.

**Pull request merged**
